name = "naasrating"
main = "src/index.js"
compatibility_date = "2024-03-26"

[[d1_databases]]
binding = "DB"
database_name = "naas_db"
database_id = "b1bcff9c-4881-4f56-af06-b68b90987c36"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

